### ISSUE TITLE
Setup Domoticz

### ISSUE THREAD

**Issue by pornstrup** [RvMp/multical402-4-domoticz#1]
How do you setup Domoticz to receive data from the script? Im total noob regarding Domoticz. Thanks

**Comment by ronaldvdmeer** [comment]
Create a dummy device on the hardware setup page
After creating this it will give you the option to create virtual devices.
Create a virtual device and write down the unique iD. 

This ID should be used when executing the multical402-4-domoticz script from the command line.
It will use the Domoticz API to update the value for the virtual device

See: https://www.domoticz.com/wiki/Virtual_meter
