### ISSUE TITLE
Superfluous sensor reading

### ISSUE THREAD

**Issue by tvwerkhoven** [RvMp/multical402-4-domoticz#2]
Thanks for your PyKamstrup port for Multical energy meters! When adapting this for influxdb, I noticed you are superfluously querying your energy meter, thus depleting the battery faster than needed (up to 30x more than needed).

You loop over all (30) multical variables here and query them, but only parse the ones issued on the command line (~1-2?), see:
https://github.com/ronaldvdmeer/multical402-4-domoticz/blob/f6aa7b9351a0f37fa265f68b05417e01586851b0/multical402-4-domoticz.py#L315-L335

To fix, only loop over command line variables or only query the sensor in the inner loop.

**Comment by ronaldvdmeer** [comment]
Thank you @tvwerkhoven for bringing this to my attention. I don't have the multical402 any longer. Are you able to test the pull request i've created?
